#! /bin/sh

mkdir -p ../static/js
../node_modules/pegjs/bin/pegjs --export-var window.FICSPARSER --format globals -o ../static/js/ficsparser.js fics_parser.peg.js
../node_modules/pegjs/bin/pegjs --export-var window.MOVESPARSER --format globals -o ../static/js/movesparser.js moves_parser.peg.js
